name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: false  # 已禁用 - 持续失败且发送邮件通知太烦人
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Tidy
      run: go mod tidy

    - name: Build
      run: go build -o /dev/null ./...
